---
# =============================================================================
# Production Overlay - Wallet Service
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orange-wallet

resources:
  - ../../base/wallet-service

images:
  - name: teukumunawar/orange-wallet-wallet-service
    newName: docker.io/teukumunawar/orange-wallet-wallet-service
    newTag: latest  # CI/CD will update this with commit SHA
