---
# =============================================================================
# Production Overlay - Transaction Service
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orange-wallet
resources:
  - ../../base/transaction-service
images:
  - name: teukumunawar/orange-wallet-transaction-service
    newName: docker.io/teukumunawar/orange-wallet-transaction-service
    newTag: 04a50f5b59e6b3156e009ab5b830ba661c969856 # CI/CD will update this with commit SHA
