---
# =============================================================================
# Production Overlay - Notification Worker
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orange-wallet

resources:
  - ../../base/notification-worker

images:
  - name: teukumunawar/orange-wallet-notification-worker
    newName: docker.io/teukumunawar/orange-wallet-notification-worker
    newTag: latest  # CI/CD will update this with commit SHA
