---
# =============================================================================
# Redis - Kustomization
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database

resources:
  - configmap.yaml
  - statefulset.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: redis
      app.kubernetes.io/version: "7"
      app.kubernetes.io/component: cache
      app.kubernetes.io/part-of: orange-wallet
      app.kubernetes.io/managed-by: kustomize
