---
# =============================================================================
# Production Overlay - API Gateway
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orange-wallet
resources:
  - ../../base/api-gateway
images:
  - name: teukumunawar/orange-wallet-api-gateway
    newName: docker.io/teukumunawar/orange-wallet-api-gateway
    newTag: a9fa2f9160af390f8233605d773938f171965e5d # CI/CD will update this with commit SHA
