apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orange-wallet

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - secret.yaml

labels:
  - pairs:
      app.kubernetes.io/name: waha
      app.kubernetes.io/component: messaging
      app.kubernetes.io/part-of: orange-wallet