---
# =============================================================================
# Kustomization - Prometheus
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - statefulset.yaml
  - service.yaml
  - configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: observability
      app.kubernetes.io/component: metrics
