apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - prometheus-rbac.yaml
  - configmap.yaml
  - statefulset.yaml
  - service.yaml
  - cadvisor-daemonset.yaml
  - cadvisor-service.yaml
  - node-exporter.yaml
  - kube-state-metrics.yaml
  - alertmanager-configmap.yaml
  - alertmanager-statefulset.yaml
  - alertmanager-service.yaml


labels:
  - pairs:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: observability
      app.kubernetes.io/component: metrics
