apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messaging

resources:
  - service.yaml
  - statefulset.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: orange-wallet-infrastructure
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
