apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - install.yaml
  - cluster-issuer.yaml
  - certificate.yaml
  - cloudflare-api-token-secret.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: orange-wallet-infrastructure
