---
# =============================================================================
# Production Overlay - User Service
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orange-wallet
resources:
  - ../../base/user-service
images:
  - name: teukumunawar/orange-wallet-user-service
    newName: docker.io/teukumunawar/orange-wallet-user-service
    newTag: a0eb511bafa1e3673acb223cefe018d225a65e0c # CI/CD will update this with commit SHA
