---
# =============================================================================
# PostgreSQL - Kustomization
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database

resources:
  - configmap.yaml
  - statefulset.yaml
  - service.yaml
  - backup-cronjob.yaml

labels:
  - pairs:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: postgresql
      app.kubernetes.io/version: "16"
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: orange-wallet
      app.kubernetes.io/managed-by: kustomize
