---
# =============================================================================
# Kustomization - API Gateway
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orange-wallet

commonLabels:
  app.kubernetes.io/name: api-gateway
  app.kubernetes.io/part-of: orange-wallet
  app.kubernetes.io/managed-by: kustomize

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml

images:
  - name: api-gateway
    newName: docker.io/teukumunawar/orange-pay-api-gateway
    newTag: latest
