---
# =============================================================================
# Kustomization - MongoDB
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database

resources:
  - statefulset.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: mongodb
      app.kubernetes.io/part-of: orange-wallet
      app.kubernetes.io/managed-by: kustomize
