---
# =============================================================================
# Kustomization - Grafana
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - deployment.yaml
  - service.yaml
  - configmap-datasources.yaml
  - configmap-dashboard-providers.yaml
  - configmap-dashboards.yaml
  - ingress.yaml
  - secret.yaml

labels:
  - pairs:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: observability
      app.kubernetes.io/component: visualization
