---
# =============================================================================
# Kustomization - Grafana
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - https://github.com/grafana/grafana-operator/releases/download/v5.20.0/kustomize-namespace_scoped.yaml  

  - deployment.yaml
  - service.yaml
  - configmap-datasources.yaml
  - configmap-dashboard-providers.yaml
  - configmap-dashboards.yaml
  - configmap-dashboards-advanced.yaml
  - configmap-dashboards-infrastructure.yaml
  - ingress.yaml
  - secret.yaml


  - configmap-telegram.yaml
  - alert-rule.yaml
  - notification.yaml

labels:
  - pairs:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: observability
      app.kubernetes.io/component: visualization
