---
# =============================================================================
# Production Overlay - ML Engine
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orange-wallet
resources:
  - ../../base/ml-engine
images:
  - name: teukumunawar/orange-wallet-ml-engine
    newName: docker.io/teukumunawar/orange-wallet-ml-engine
    newTag: 054226d511b8e0dd46550d8980607ff25de1bfb1 # CI/CD will update this with commit SHA
