---
# =============================================================================
# Kustomization - Notification Worker
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orange-wallet

resources:
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: notification-worker
      app.kubernetes.io/part-of: orange-wallet
      app.kubernetes.io/managed-by: kustomize
